### ISSUE TITLE
R version typo?

### ISSUE THREAD

**Issue by wtagr** [mandymejia/ciftiTools#10]
Hi,

Thanks so much for contributing this to R.

When installing, an error occurs: "this R is version 3.6.0, package 'ciftiTools' requires R >= 3.50"

I am not sure this error just happened on my machine, but could you please update 'Depends: R (>= 3.50)' in the DESCRIPTION file to 'Depends: R (>= 3.5.0)'？It seems that would be more compatible.

Thank you,
Meng

**Comment by damondpham** [comment]
Thanks for letting us know about this Meng! I just fixed this--please tell me if you encounter any other problems. Thanks again!
