### ISSUE TITLE
Expanded demonstration: Computing parcellated seed correlations: fmriscrub won't compile

### ISSUE THREAD

**Issue by dkp** [mandymejia/ciftiTools#41]
fMRIscrub problems (a complete log is attached): 

R version 4.2.0 (2022-04-22)
OSX Catalina 10.15.7

`install.packages("fMRIscrub")`
Warning in install.packages :
package ‘fMRIscrub’ is not available for this version of R

---
`install.packages("devtools")` 
This seems to go alright.

---
`devtools::install_github("mandymejia/fMRIscrub")`
[fmriscrub_install.txt](https://github.com/mandymejia/ciftiTools/files/8849322/fmriscrub_install.txt)

It is trying to install from source  and can't find gfortran
ERROR: compilation failed for package ‘fMRIscrub’
* removing ‘/Library/Frameworks/R.framework/Versions/4.2/Resources/library/fMRIscrub’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/34/ylkzx8hn52q2p5d_23pc90ww0000gn/T//Rtmp0tbJin/filedef5716135e/fMRIscrub_0.10.0.tar.gz’ had non-zero exit status

**Comment by damondpham** [comment]
Thank you for opening this issue @dkp!

Yes, unfortunately we have had trouble adding `fMRIscrub` back to CRAN. So it needs to be downloaded from GitHub.

Furthermore, for Mac OS there is sometimes a problem with the C++ code in the package. So you can instead download the latest version without any C++ code:

`devtools::install_github("mandymejia/fMRIscrub", ref="10.0_noCPP")`

Let me know if that works?

**Comment by dkp** [comment]
Thanks so much!  I've attached the accompanying log of the install.  But the short version is, this seemed to work!
[fmriscrub2.txt](https://github.com/mandymejia/ciftiTools/files/8864054/fmriscrub2.txt)

**Comment by damondpham** [comment]
Great! Thank you for looking into the expanded demo! I hope we can get `fMRIscrub` back on CRAN soon.
