### ISSUE TITLE
Issue in connecting to workbench in R on Mac, error message "'wb_command' cannot be opened because the developer cannot be verified."

### ISSUE THREAD

**Issue by guzhiling** [mandymejia/ciftiTools#42]
Hi, I encountered this issue during the setup of ciftiTools on macOS. Below is my sessionInfo:

      R version 4.1.3 (2022-03-10)
      Platform: x86_64-apple-darwin17.0 (64-bit)
      Running under: macOS Monterey 12.2.1

Everything works on my windows machine, but I could not figure out how to solve this issue on OSX machine. Note: I tried ctrl+click the command file, but it seems I cannot grant security exception to it. Thank you for your attention! 

<img width="259" alt="Screen Shot 2022-06-10 at 2 23 44 PM" src="https://user-images.githubusercontent.com/37173670/173135964-45657ef2-e830-4c80-b8bf-4f253b4dc4d4.png">

**Comment by damondpham** [comment]
Hello @guzhiling! 

I'm sorry to hear about this problem, and I have not encountered it myself. 

This is the most helpful link I found: https://www.alphr.com/cannot-be-opened-because-the-developer-cannot-be-verified/ . Could you try some of the solutions it proposes?

Also, just making sure: you downloaded the Mac version of the Workbench from this link? https://www.humanconnectome.org/software/get-connectome-workbench

**Comment by guzhiling** [comment]
Hi @damondpham , Thank you for your reply! 
I solved this problem by overriding the default security setting through the following process:

System Preference -> Security and Privacy -> General -> Unlock -> Allow apps to download from App Store and identified developers -> Manually click all the command files in 'workbench/bin_macosx64' one by one (fig 1) -> Ignore the error message and go back to System Preference to Grant access for each file by clicking "open anyway"(fig2). 

fig1: 
<img width="400" alt="Screen Shot 2022-06-16 at 12 30 00 PM" src="https://user-images.githubusercontent.com/37173670/174131283-42ae642e-5273-473e-a158-7a890f73dd1c.png">

fig2: 
![image](https://user-images.githubusercontent.com/37173670/174131798-d7c397ac-e9ba-499f-9e89-dea5f3bcbbbf.png)

Hope it would help someone else who is using this!

**Comment by damondpham** [comment]
I'm glad you were able to work around that issue! And thanks a lot for posting the solution for others.
