### ISSUE TITLE
Add Schaefer 200 parcellation

### ISSUE THREAD

**Issue by GerardYu** [mandymejia/ciftiTools#45]
hi would it be possible to add the schaefer 200 parcellation to the load_parc function

**Comment by damondpham** [comment]
Hello @GerardYu !

Thanks for reaching out. I think it's possible, but the package is already pushing the memory limits for CRAN, so we would prefer not to unless it would greatly help our user base. Would making the 200 parcellation available through `load_parc` allow for a much more convenient workflow for you? (Versus downloading the .dlabel file and reading it in.)

**Comment by GerardYu** [comment]
I'm not sure how to load the atlas manually using the .dlabel file. But yes if you can include the 200 parcellation in the load_parc function, that would really make things a lot easier for me

**Comment by damondpham** [comment]
Oh okay! Loading the atlas manually might be quite simple, so let's try that first. 

Go here to find the dlabel file: https://github.com/ThomasYeoLab/CBIG/tree/master/stable_projects/brain_parcellation/Schaefer2018_LocalGlobal/Parcellations/HCP/fslr32k/cifti

Perhaps the one you want is `Schaefer2018_200Parcels_Kong2022_17Networks_order.dlabel.nii`.

You can read this into ciftiTools like so:
```
parc <- read_cifti("Schaefer2018_200Parcels_Kong2022_17Networks_order.dlabel.nii")
```

Let me know if this works fine for you!

**Comment by GerardYu** [comment]
oh yes that works for me!
