### ISSUE TITLE
Show Glasser360 parcellation

### ISSUE THREAD

**Issue by zqsha** [mandymejia/ciftiTools#48]
Hi expert, 
I recently do some fMRI analyses using Glasser360 parcellation. Based on the original paper, it mentioned that several cortical parcellations are included for convenience: the Schaefer parcellation at 100, 400, or 1000 parcels resolutions (Schaefer et al., 2018), and the Yeo parcellation at 7 networks (51 components) or 17 networks (114 components) resolutions (Thomas Yeo et al., 2011). But it does not mention Glasser360 parcellation. Is it available to show?
Thanks,
Cain

**Comment by damondpham** [comment]
Hello Cain! 

You can load any parcellation if you have the file for it by using `read_cifti(the_file_name)`. Otherwise, we've only included a few parcellations in the package to be loaded with `load_parc(name_of_parcellation)` for convenience. 

Here's a sketch of these two diferent ways:

```
# Load ciftiTools and the workbench.
library(ciftiTools)
ciftiTools.setOption("wb_path", "~/Desktop/workbench")

# Load the parcellation two ways:
#   using the file included in `ciftiTools`
#   reading your own file
parcA <- load_parc("Schaefer_400")
parcB <- read_cifti("~/Desktop/Schaefer_400.dlabel.nii")
identical(parcA$data, parcB$data) # TRUE
```

If you don't already have the Glasser360 parcellation, I think I found a copy here for you: https://github.com/sina-mansour/neural-identity/blob/master/data/templates/atlas/Glasser360.32k_fs_LR.dlabel.nii

So you can download this file and then read it in with `read_cifti`.

Let me know if you have any more questions~

**Comment by zqsha** [comment]
Hi expert,
Thanks for your reply. Now I can read this Glasser360.32k_fs_LR.dlabel.nii by using read_cifti function and show the parcellation by 'plot' function. Now I have 360 values revived from structural analysis on Glasser360 parcellation, how can I show these? This time I wanted to show the results from the parcellation, instead of only showing the parcellation. I assigned these values to parc$data, however, it still does not show these values. Do you have any thoughts on it? Thanks

Best,
Cain

**Comment by zqsha** [comment]
Yes, sure. Below are the values that I wanted to present. So, we can see there are 360 values, separately corresponding to 360 parcels in Glasser atlas. Thank you so much for your help. I really appreciated it.
[brain_phenotype.txt](https://github.com/mandymejia/ciftiTools/files/11224696/brain_phenotype.txt)

**Comment by damondpham** [comment]
Hi Cain, in the above comment I have a demo script that should work. Try it out and let me know what you think?

Something to note is that in the parcellation the right hemisphere parcels are listed first in the label keys, whereas in the phenotype value table the left hemisphere parcels are listed first. So I used `match` to make sure the values are mapped correctly.

**Comment by damondpham** [comment]
Hi Cain,

I'm glad I was able to help!

For your first question:

```
# Add very inflated surfaces
#   (By default, if `xii` does not have a surface, the plot function
#   automatically adds inflated surfaces. So if you want to use the
#   very inflated surface instead, you have to add it to `xii`.
#   This function also accepts file paths to surface geometry GIFTIs
#   if you have your own surface file that you'd like to use.)
xii <- add_surf(xii, surfL="very inflated", surfR="very inflated")
```

For your second question: I think it is yellow because the `"xifti"` object you are plotting has dlabel data, and the color for that parcel according to the label table is yellow. There's at least two ways to change the color: you can modify the values in the label table (`xii$meta$cifti$labels[[1]]`), or you can convert the `"xifti"` to a dscalar and then back to a dlabel while assigning it a new label table with the desired color. If you'd like, send me a copy of the `"xifti"` object (for example with `saveRDS`) and I can show you both ways. 

Let me know if I can give any other advice!

**Comment by zqsha** [comment]
Hi expert,
Thank you so much for your reply. 
Regarding Question 1: Do you have any thoughts about how to add "very inflated" surface to xii?
Regarding Question 2: Sorry about the question that misleads you. For example, after analyzing data, I wanted to highlight some significant regions with the same color (e.g. red). It's like a binary mask. Do you have any ideas about how to show these ROIs with the same color?

Thanks,
Cain

**Comment by damondpham** [comment]
Q1: Yes, so the code I posted above should add the "very inflated" surface to your `xifti` object:

```
xii <- add_surf(xii, surfL="very inflated", surfR="very inflated")
```

Q2: Okay, so you have binary `xii` data, and you want to plot it--you should use `convert_xifti` to convert the "xifti" object to a dlabel. If you send me your data, I can show you an example.

**Comment by zqsha** [comment]
OK, thanks, get it. Below is the xii with binary data. Please feel free to revise it. Thank you so much.
PS. when I upload .rds (or Rdata), github seems not support the file type, so I used zip file type.

[test.zip](https://github.com/mandymejia/ciftiTools/files/11250531/test.zip)

**Comment by damondpham** [comment]
Could you upload it to Google Drive and send me a download link instead? When I unzip the file, the data gets corrupted or something (on a Mac).

**Comment by damondpham** [comment]
Hi Cain,

Okay, actually by downloading it on Windows I was able to look at your data.

So you have a dscalar "xifti" with binary data. In this code, I convert it to a dlabel and ask for the second value (because the first value is assigned to be white) to be red. 

```
# use `?convert_xifti` to see the options
xii <- convert_xifti(xii, "dlabel", colors=c("red"))
plot(xii)
```

Hope this helps! Let me know if you have more questions.

**Comment by zqsha** [comment]
Hi expert,
OK, great. Thanks, now it's working very well. When I plot the brain maps, I find there are two color bars, as follows:
![image](https://user-images.githubusercontent.com/27337033/232578972-b54d3610-86b2-4be5-b88a-7a0d8c9f8fdf.png)
![image](https://user-images.githubusercontent.com/27337033/232579025-5cc0f732-1335-414f-9d99-bf4c7cf12d57.png)

I am not sure whether I can select another color bar. Is there any other options that I can pick? Thank you so much.

**Comment by damondpham** [comment]
Yes, there are a lot of options! If you do `?view_xifti_surface` you can see the help page explaining how to use the `colors` argument to change the colors.

Try it out, and let me know if you have follow-up questions!

**Comment by zqsha** [comment]
OK, great, thank you so much for your generous help. I will let you know once I have additional questions.
Best,
Cain

**Comment by zqsha** [comment]
Hi expert,
I have a question about setting the color. For example, I plotted a brain map with statistical values, so we can see some regions (e.g, dark blue regions) do not show significance. How can I set the color of these nonsignificant regions as the background color on the brain (e.g, light grey)?
![Capture](https://user-images.githubusercontent.com/27337033/233862554-316416bc-d6c2-4ee1-b4e2-def79f6af6f3.PNG)
Do you have any suggestions? 

Thanks,
Cain

**Comment by damondpham** [comment]
Hi Cain,

You can use the `move_to_mwall` function with `values=0` to mask out all data locations that have a value exactly equal to zero. If you also want to mask out values close to but not exactly zero, you can do some rounding first with `transform_xifti`.

**Comment by zqsha** [comment]
Thanks for your helpful suggestions!!! It's now working very well. :-)

**Comment by damondpham** [comment]
Great! Don't hesitate to reach out for any more questions.

**Comment by damondpham** [comment]
Hi Cain,

Sure! There's two options:

If you make an interactive plot (Open GL window or a widget), you can drag the brains to rotate them. But this is imprecise and doesn't translate well to saving an image. 

The other option is to use `rotate_surf`. You should load your desired surfaces, use `rotate_surf` to rotate them as necessary, and then attach them to your `"xifti"` object with `add_surf`. Then, when you do `view_xifti_surface`, these rotated surfaces will be used.

I played around with the second option; here's code that seems to get the perspective you want:

```
xii <- load_parc()
xii <- add_surf(xii, rotate_surf(load_surf(), r2=1.6), rotate_surf(load_surf("right"), r2=-1.6))
plot(xii, view="lateral")
```

Let me know if that works!

**Comment by zqsha** [comment]
Thanks for your helpful suggestions. Now, it's working very well.

**Comment by damondpham** [comment]
Gonna close this Issue for now, but do open a new one if you have another question!
