### ISSUE TITLE
Global signal regression

### ISSUE THREAD

**Issue by GerardYu** [mandymejia/ciftiTools#50]
Hi i'm not sure if this is the right place to ask, but is there a way to carry out global signal regression on the dtseries.nii files

**Comment by damondpham** [comment]
Hi, yes this is a fine place to ask!

It's not possible to do GSR directly on the CIFTI files using the Connectome Workbench (according to a response I received last year: https://groups.google.com/a/humanconnectome.org/g/hcp-users/c/-xdWSg_lrkY). So `ciftiTools` is a good option for conducting GSR. 

Here are the steps I would take:

1. Read in the dtseries CIFTI file into R as a `"xifti"` object with `read_cifti`.
2. Save the matrix data to another variable with `as.matrix`
3. Apply the `nuisance_regression` function from our other package, `fMRItools`, to the matrix data: https://github.com/mandymejia/fMRItools/blob/main/R/nuisance_regression.R 
4. Use `newdata_xifti` to move the nuisance-regressed data back into the `"xifti"` object. Done!

Let me know if you have any further questions. I could also make a demo script for you if you have example data to share.

**Comment by GerardYu** [comment]
thanks, that works!
