### ISSUE TITLE
Remove colorbar

### ISSUE THREAD

**Issue by zqsha** [mandymejia/ciftiTools#51]
Hi expert,
I just have a couple of questions about ciftiTools. 
1. Is it possible to remove colorbar from the figure?
2. Can I increase the font size of title in the figure?
3. For the colorbar, is it possible to add text on the colorbar, for example adding some text about what this colorbar represents?

Thanks for your feedback.

**Comment by damondpham** [comment]
Hi @zqsha!

Here's an example where the colorbar is not included, and the font size of the title is larger:

`plot(xii, legend_embed=FALSE, cex.title=3, title="My Large Title")`

More information about the available arguments can be displayed like so: 

`?view_xifti_surface`

but we currently don't provide an option to add text to the colorbar.

Let me know if you have any more questions!
