### ISSUE TITLE
Is it possible to manupluate data based on MNI coordinates?

### ISSUE THREAD

**Issue by JAQuent** [mandymejia/ciftiTools#53]
Hello everyone, 
I am wondering: a) How to get the MNI coordinates for each row of the subcortical data? b) How would I e.g. build speherical ROIs based on MNI coordinates?

Best,
Alex

**Comment by JAQuent** [comment]
In the paper, it says "_Subcortical voxel locations and brain structure labels, in contrast, are contained in the CIFTI XML."_ but how do I access this information? When using `info_cifti()` it doesn't seem to contain it. 

What I essentially looking for is a 31870 by 3 matrix where the columns correspond to the x, y and z coordinates of the subcortical voxels.

**Comment by JAQuent** [comment]
I found a way and will post this myself here later.

**Comment by JAQuent** [comment]
I think I found a way. I wrote a blog post on this that can be found here if someone else is wondering the same thing: https://jaquent.github.io/2023/07/a-way-to-get-mni-coordinates-for-subcortical-voxels-of-a-cifti-file/

The MNI coordiantes can be downloaded https://gist.github.com/JAQuent/b1abc8e5e3375d461850eb641efde601

Feel free to check I got something wrong there.

**Comment by damondpham** [comment]
Hi @JAQuent thanks very much for looking into this problem and writing a vignette to share your work with others!! 

Actually, I think a `"xifti"` object's subcortical metadata has enough info to construct `VoxelIndicesIJK`, though it's not saved directly. Would you mind checking for me that this gives the exact same value?

`which(x$meta$subcort$mask, arr.ind=TRUE)`

where `x` is your `"xifti"` object.

Also to answer the question about the transformation matrix and having to add a column of 1's: the column of 1's performs the translation; the previous 3 columns does scaling and rotation (but the submatrix consisting of the first three rows&cols is diagonal, so it really just does scaling).

**Comment by JAQuent** [comment]
Hey there seems to be slight differences a) the ordering is different but that can be solved. b) when I compare the mean of the whole  matrices as a quick check to see if they are the same I get  36.9826 (in the XML-based method) and 37.9826, so the difference is that on average the indices are exactly 1 more per cell. 

This actually fits when I look the matrices:

Here is the matrix that I got  from the XML information for the brain stem values: 
```
     [,1] [,2] [,3]
[1,]   42   41    0
[2,]   43   41    0
[3,]   44   41    0
[4,]   45   41    0
[5,]   46   41    0
[6,]   47   41    0
```

while here is the matrix we get from the brain mask:
```
     dim1 dim2 dim3
[1,]   43   42    1
[2,]   44   42    1
[3,]   45   42    1
[4,]   46   42    1
[5,]   47   42    1
[6,]   48   42    1
```

They are clearly the same values just that for the second method you have to subtract one. I'll actually update the vignette.

**Comment by damondpham** [comment]
Oh perfect! Yeah, it should be limited to those differences if my memory was correct. Thanks very much for checking for me; I'll be adding this info to the README :)
