### ISSUE TITLE
view_cifti_surface material

### ISSUE THREAD

**Issue by Bramdiamond** [mandymejia/ciftiTools#55]
How can I change the lighting while using view_cifti_surface()?

Per the documentation, I've tried the following:
`view_cifti_surface(dice_summary_xii, zlim = c(0, 1), title = "Dice Summary", material = list(lit=FALSE, smooth=FALSE))`

**Comment by damondpham** [comment]
Hi @Bramdiamond I think that should work actually! Are you using the newest version? You could send me `dice_summary_xii` via Google Drive as an `.rds` file for me to take a more exact look.

**Comment by Bramdiamond** [comment]
Thanks for taking a look, @damondpham !

I'm using `ciftiTools version 0.12.2`

Here is [the RDS file](https://drive.google.com/file/d/1lo9qyqH-hDG4ZKN_ax46OHU5FIFredhO/view?usp=drive_link).

**Comment by damondpham** [comment]
@Bramdiamond  could you add damondpham@gmail.com to the permissions? Or make that file public :)

**Comment by damondpham** [comment]
Hi @Bramdiamond it seems to be working for me:
> view_cifti_surface(dice_summary_xii, zlim = c(0, 1), title = "Dice Summary (regular lighting)")
> view_cifti_surface(dice_summary_xii, zlim = c(0, 1), title = "Dice Summary", material = list(lit=FALSE, smooth=FALSE))

<img width="1346" alt="Screen Shot 2023-08-18 at 1 49 25 PM" src="https://github.com/mandymejia/ciftiTools/assets/14958204/c859671e-0071-4509-817d-7d0b870d6f7a">

Is this what you see? If not, try double-checking the `material` argument in your script? And the package version: if you do `?view_cifti_surface` in the same script you're working in you should see the `material` argument in the documentation. That's all I can think of...
