### ISSUE TITLE
Is there a way with ciftiTools to create cifti masks for the subcortex based on MNI nifti images 

### ISSUE THREAD

**Issue by JAQuent** [mandymejia/ciftiTools#61]
Suppose I have a MNI mask for some subcortical ROI, is there a way for me to use ciftiTools to create a .dscalar/.dlabel.nii cifti ROI that I can use for analyses?

**Comment by damondpham** [comment]
Hey Alex! I would do something like this:

```
xii <- ciftiTools:::template_xifti() # initialize empty xifti
xii_subParc <- ciftiTools:::load_sub_parc() # load subcortical parcellation
xii$data$subcort <- myDataMatrix # put data values
xii$meta$subcort$labels <- factor(
  rep("Other", nrow(myDataMatrix)), 
  levels=levels(xii_subParc$meta$subcort$labels)
) # name the ROI as 'Other', unless an existing option is appropriate
xii$meta$subcort$mask <- myDataMask # put the mask
```

Then `is.xifti()` should be `TRUE`! If the mask is 91 x 109 x 91 like our MNI template, you would also be able to plot and visualize the ROI. Either way, this should be able to be written out to CIFTI and used in analysis.

**Comment by JAQuent** [comment]
This was very helpful. Thank you! I will soon make a tiny blog post about this but to quickly share my solution for other people running into this issue here is what I did in the end:

```
# Create empty xifti based on this template
new_xii <- newdata_xifti(temp_xii, 0)
ROI_nii <- readNIfTI("E:/Seafile/imaging_results/Midbrain_Atlases_all/mean_fullMB.nii.gz")
ROI_nii <- cal_img(ROI_nii) # Not sure if this is necessary
# Use the subcortical mask of the cifti file to create a one-dimensional matrix/vector
subcort_mask   <- new_xii$meta$subcort$mask
subcort_matrix <- ROI_nii_bin[subcort_mask]

# Add this as new data to the xifti object
new_xii$data$subcort <- matrix(subcort_matrix, nrow = length(subcort_matrix), ncol = 1)
```

This produces this, which looks like what I want:
![image](https://github.com/mandymejia/ciftiTools/assets/17894303/3e60ac95-c74c-4f8f-8601-fb2492a1f6db)
